name: hyperion
dependencies:
# These are required
 - python>=3.7
 - numpy>=1.14
 - scipy
 - sphinx
 - pyqt>=5.9.2
 - qt=5
 - pyqtgraph
 - netcdf4
 - pip>=19
 - pip:
   - pyyaml>=5.1
   - lantzdev
   - sphinx_rtd_theme
   - lantz_core
   - lantz_drivers
   - lantz_qt
   - lantz_sims
   - https://github.com/qpit/thorlabs_apt/archive/master.tar.gz
   - pyvisa-py
   - pyserial