Instruments:
  BeamFlags:
    port: COM4
    dummy: False
    instrument: hyperion.instrument.beam_flags.beam_flags_instr/BeamFlags
    controller: hyperion.controller.generic.generic_serial_contr/GenericSerialController
    view: hyperion.view.beam_flags.beam_gui/BeamFlagsGui
    flag_states:
      red: 'r'           # character for arduino red state
      green: 'g'         # character for arduino green state
    gui_red_color: rgb(255, 100, 100)
    gui_green_color: rgb(100, 255, 100)
    gui_state_update_ms: 100    # recommend 100,  update time in ms for the state indicators
    gui_flags:
      '1':          # key-name should be the id-character for the arduino controller
        name: Pump
        red_name: Blocked
        green_name: Open
        shortkey: Ctrl+1
      '2':
        name: Probe
        red_name: Blocked
        green_name: Open
        shortkey: Ctrl+2