name: Hydraharp
settings:
 SYNCDIVMIN: 1
 SYNCDIVMAX : 16
 ZCMIN : 0 
 ZCMAX : 40
 DISCRMIN : 0
 DISCRMAX : 1000
 CHANOFFSMIN : -99999
 CHANOFFSMAX : 99999
 OFFSETMIN : 0
 OFFSETMAX : 500000
 ACQTMIN : 1
 ACQTMAX : 360000000
 STOPCNTMIN : 1
 STOPCNTMAX : 4294967295
 HOLDOFFMIN : 0
 HOLDOFFMAX : 524296
 LIB_VERSION : "3.0"
 MAXDEVNUM : 8
 HHMAXINPCHAN : 8
 BINSTEPSMAX : 26
 MAXHISTLEN : 65536
 MAXLENCODE : 6
 MAXHISTLEN_CONT : 8192
 MAXLENCODE_CONT : 3
 MAXCONTMODEBUFLEN : 262272
 TTREADMAX : 131072
 TTREADMIN : 128
