controller: hyperion.controller.agilent.agilent33522A/Agilent33522A
defaults:
    - channel: 1
      current_use: EOM modulation
      output: True
      waveform:
        function: SQU
        frequency: 0.25Hz
        high: 0.3V
        low: -0.3V
      limit_high: 1V
      limit_low: -1V
    - channel: 2
      current_use: AOTF external modulation
      output: False
      waveform:
        function: SIN
        frequency: 30kHz
        high: 9.9V
        low: 0V
      limit_high: 9.85V
      limit_low: 0.01V
