User:
  name: Martin

Instruments:
  - VariableWaveplate:
      port: COM8
      instrument: hyperion.instrument.variable_waveplate.variable_waveplate/VariableWaveplate
      controller: hyperion.controller.thorlabs.lcc25/Lcc
      dummy: True
      enable: True
      settings: # not implemented yet
        output: True
        voltage1: 1V
        voltage2: 1V
  - ExampleInstrument:
      port: COM0
      instrument: hyperion.instrument.example_instrument/ExampleInstrument
      controller: hyperion.controller.example_controller/ExampleController
      dummy: True
      settings:
        output: True
  - ThorlabsMotor:
      xMotor: 83817644
      yMotor: 83815760
      zMotor: 83815758
      testMotor: 83817677
      piezoMotor: 81818266
  
  
   
Data:
  save_folder: D:/mcaldarola/Data/2019-04-17_hyperion/
  data_type: txt

Scan:
  mode: voltage1
  sync: automatic
  channel: 1
  start: 1V
  stop: 2V
  step: 100mV
  delay: 0.01s
  detectors:
    - detector1:
        channel: 1
