User:
  name: Martin

Instruments:
  HydraHarp:
    port: COM0
    mode: Histogram
    clock: Internal
    devidx: 0
    instrument: hyperion.instrument.correlator.hydraharp_instrument/HydraInstrument
    controller: hyperion.controller.picoquant.hydraharp/Hydraharp
    view: hyperion.view.hydraharp.hydraharp_gui/App
    graphView: hyperion.view.hydraharp.hydraharp_gui/DrawHistogram
  ExampleInstrument:
    port: COM0
    instrument: hyperion.instrument.example_instrument/ExampleInstrument
    controller: hyperion.controller.example_controller/ExampleController
    view: hyperion.view.simple_gui_examples.example_gui/ExampleGui
    dummy: True
    settings:
      output: True
  ExampleInstrument_2:
    port: COM0
    instrument: hyperion.instrument.example_instrument/ExampleInstrument
    controller: hyperion.controller.example_controller/ExampleController
    view: hyperion.view.simple_gui_examples.example_gui/ExampleGui
    dummy: True
    settings:
      output: True
  ExampleInstrument_3:
    port: COM0
    instrument: hyperion.instrument.example_instrument/ExampleInstrument
    controller: hyperion.controller.example_controller/ExampleController
    view: hyperion.view.simple_gui_examples.example_gui/ExampleGui
    dummy: True
    settings:
      output: True
  ExampleInstrument_4:
    port: COM0
    instrument: hyperion.instrument.example_instrument/ExampleInstrument
    controller: hyperion.controller.example_controller/ExampleController
    view: hyperion.view.simple_gui_examples.example_gui/ExampleGui
    dummy: True
    settings:
      output: True
  ExampleInstrument_5:
    port: COM0
    instrument: hyperion.instrument.example_instrument/ExampleInstrument
    controller: hyperion.controller.example_controller/ExampleController
    view: hyperion.view.simple_gui_examples.example_gui/ExampleGui
    dummy: True
    settings:
      output: True
  OsaInstrument:
    port: AUTO
    instrument: hyperion.instrument.osa.osa_instrument/OsaInstrument
    controller: hyperion.controller.osa.osa_controller/OsaController
    view: hyperion.view.osa.osa_view/App
    graphView: hyperion.view.osa.osa_view/DrawSpectrum
    dummy: False
  Gui_with_graph:
    port: COM0
    instrument: hyperion.instrument.example_instrument/ExampleInstrument
    controller: hyperion.controller.example_controller/ExampleController
    graphView:  hyperion.view.simple_gui_examples.gui_with_graph/App
    dummy: True
    settings:
      output: True
  ExampleInstrument_7:
    port: COM0
    instrument: hyperion.instrument.example_instrument/ExampleInstrument
    controller: hyperion.controller.example_controller/ExampleController
    graphView: hyperion.view.osa.osa_view/DrawSpectrum
    dummy: True
    settings:
      output: True
  ExampleInstrument_8:
    port: COM0
    instrument: hyperion.instrument.example_instrument/ExampleInstrument
    controller: hyperion.controller.example_controller/ExampleController
    graphView: hyperion.view.osa.osa_view/DrawSpectrum
    dummy: True
    settings:
      output: True

MetaInstruments:
  SampleXyzStage:
    x: xMotor
    y: yMotor
    z: zMotor

Measurements:
  #specific for this experiment
  #list of measurement views which need to be loaded and accesible for the main experiment class.
  exampleMeasurement:
    view: examples.measurement_gui/App
    graphView: hyperion.view.osa.osa_view/DrawSpectrum

Data:
  save_folder: D:/mcaldarola/Data/2019-04-17_hyperion/
  data_type: txt

Scan:
  mode: voltage1
  sync: automatic
  channel: 1
  start: 1V
  stop: 2V
  step: 100mV
  delay: 0.01s
  detectors:
    - detector1:
        channel: 1
