User:
  name: Martin

Instruments:
  - VariableWaveplate:
      port: COM8
      instrument: hyperion.instrument.variable_waveplate.variable_waveplate/VariableWaveplate
      controller: hyperion.controller.thorlabs.lcc25/Lcc
      dummy: True
      enable: True
      settings: # not implemented yet
        output: True
        voltage1: 1V
        voltage2: 1V
  - ExampleInstrument:
      port: COM0
      instrument: hyperion.instrument.example_instrument/ExampleInstrument
      controller: hyperion.controller.example_controller/ExampleController
      dummy: True
      settings:
        output: True
  - xMotor:
      serial_number: 83817644
      instrument: hyperion.instrument.motor.thorlabs_motor_instrument/Thorlabsmotor
      controller: hyperion.controller.thorlabs.TDC001/TDC001
  - yMotor:
      serial_number: 83815760
      instrument: hyperion.instrument.motor.thorlabs_motor_instrument/Thorlabsmotor
      controller: hyperion.controller.thorlabs.TDC001/TDC001
  - zMotor:
      serial_number: 83815758
      instrument: hyperion.instrument.motor.thorlabs_motor_instrument/Thorlabsmotor
      controller: hyperion.controller.thorlabs.TDC001/TDC001
  - testMotor:
      serial_number: 83817677
      instrument: hyperion.instrument.motor.thorlabs_motor_instrument/Thorlabsmotor
      controller: hyperion.controller.thorlabs.TDC001/TDC001
  - piezoMotor:
      serial_number: 81818266
      instrument: hyperion.instrument.motor.thorlabs_motor_instrument/Thorlabsmotor
      controller: hyperion.controller.thorlabs.TDC001/TDC001
  - XYZMotor:
      instrument: hyperion.instrument.xyz_motors/ThorlabsXYZ
      view: hyperion.view.xyz_motors/Thorlabs3AxisView
      xMotor: 83815760
      yMotor: 83815758
      zMotor: 83817677
  
  
   
Data:
  save_folder: D:/mcaldarola/Data/2019-04-17_hyperion/
  data_type: txt

Scan:
  mode: voltage1
  sync: automatic
  channel: 1
  start: 1V
  stop: 2V
  step: 100mV
  delay: 0.01s
  detectors:
    - detector1:
        channel: 1
