User:
  name: Martin

Instruments:
  VariableWaveplate:
    port: COM8
    instrument: hyperion.instrument.variable_waveplate.variable_waveplate/VariableWaveplate
    controller: hyperion.controller.thorlabs.lcc25/Lcc
    view: hyperion.view.variable_waveplate.variable_waveplate_gui/VariableWaveplateGui
    dummy: True
    enable: True
    settings: # not implemented yet
      output: True
      voltage1: 1V
      voltage2: 1V
  ExampleInstrument:
    port: COM0
    instrument: hyperion.instrument.example_instrument/ExampleInstrument
    controller: hyperion.controller.example_controller/ExampleController
    view: hyperion.view.GUI_tests.example_gui/ExampleGui
    dummy: True
    settings:
      output: True
  OsaInstrument:
    port: AUTO
    instrument: hyperion.instrument.osa.osa_instrument/OsaInstrument
    controller: hyperion.controller.osa.osa_controller/OsaController
    view: hyperion.view.osa.osa_view/App
    dummy: False

Data:
  save_folder: D:/mcaldarola/Data/2019-04-17_hyperion/
  data_type: txt

Scan:
  mode: voltage1
  sync: automatic
  channel: 1
  start: 1V
  stop: 2V
  step: 100mV
  delay: 0.01s
  detectors:
    - detector1:
        channel: 1
