User:
  name: Martin

Instruments:
  VariableWaveplate:
    port: COM8
    instrument: hyperion.instrument.variable_waveplate.variable_waveplate/VariableWaveplate
    controller: hyperion.controller.thorlabs.lcc25/Lcc
    dummy: True
    enable: True
    settings: # not implemented yet
      output: True
      voltage1: 1V
      voltage2: 1V
  xMotor:
    serial_number: 83841160 #83817644
    instrument: hyperion.instrument.motor.thorlabs_motor_instrument/Thorlabsmotor
    controller: hyperion.controller.thorlabs.TDC001/TDC001
  yMotor:
    serial_number: 83850123 #83815760
    instrument: hyperion.instrument.motor.thorlabs_motor_instrument/Thorlabsmotor
    controller: hyperion.controller.thorlabs.TDC001/TDC001
  zMotor:
    serial_number: 83850111 #83815758
    instrument: hyperion.instrument.motor.thorlabs_motor_instrument/Thorlabsmotor
    controller: hyperion.controller.thorlabs.TDC001/TDC001
  XPiezoStepper:
    controller: hyperion.controller.attocube.anc350/Anc350
    instrument: hyperion.instrument.positioner.anc_instrument/Anc350Instrument
    axis_number: 0
  YPiezoStepper:
    controller: hyperion.controller.attocube.anc350/Anc350
    instrument: hyperion.instrument.positioner.anc_instrument/Anc350Instrument
    axis_number: 2
  ZPiezoStepper:
    controller: hyperion.controller.attocube.anc350/Anc350
    instrument: hyperion.instrument.positioner.anc_instrument/Anc350Instrument
    axis_number: 1
  XPiezoScanner:
    controller: hyperion.controller.attocube.anc350/Anc350
    instrument: hyperion.instrument.positioner.anc_instrument/Anc350Instrument
    axis_number: 3
  YPiezoScanner:
    controller: hyperion.controller.attocube.anc350/Anc350
    instrument: hyperion.instrument.positioner.anc_instrument/Anc350Instrument
    axis_number: 5
  ZPiezoScanner:
    controller: hyperion.controller.attocube.anc350/Anc350
    instrument: hyperion.instrument.positioner.anc_instrument/Anc350Instrument
    axis_number: 4
  Gui_with_graph:
    port: COM0
    instrument: hyperion.instrument.example_instrument/ExampleInstrument
    controller: hyperion.controller.example_controller/ExampleController
    graphView:  hyperion.view.simple_gui_examples.gui_with_graph/App
    dummy: True
    settings:
      output: True



MetaInstruments:
  SampleXyzStageMotor:
    x: xMotor
    y: yMotor
    z: zMotor

Measurements:
  #specific for this experiment
  #list of measurement views which need to be loaded and accesible for the main experiment class.
  exampleMeasurement:
    view: examples.measurement_gui/App
    graphView: hyperion.view.osa.osa_gui/DrawSpectrum
    
Data:
  save_folder: D:/mcaldarola/Data/2019-04-17_hyperion/
  data_type: txt
