User:
  name: Martin and Aron

Instruments:
  Polarimeter:
    'dll_name': 'SKPolarimeter'
    instrument: hyperion.instrument.polarization.polarization/Polarimeter
    controller: hyperion.controller.sk.sk_pol_ana/Skpolarimeter
    view: hyperion.view.polarization.polarimeter_gui/PolarimeterGui
    graphView:  hyperion.view.polarization.polarimeter_gui/Graph
    dummy: False
  VariableWaveplate:
    controller: hyperion.controller.thorlabs.lcc25/Lcc
    instrument: hyperion.instrument.variable_waveplate.variable_waveplate/VariableWaveplate
    view: hyperion.view.variable_waveplate.variable_waveplate_gui/VariableWaveplateGui
    port: COM8
    enable: False
    dummy: False
#  ExampleInstrument:
#    port: COM0
#    instrument: hyperion.instrument.example_instrument/ExampleInstrument
#    controller: hyperion.controller.example_controller/ExampleController
#    dummy: True
#    settings:
#    output: True
#  ExampleInstrument_2:
#    port: COM0
#    instrument: hyperion.instrument.example_instrument/ExampleInstrument
#    controller: hyperion.controller.example_controller/ExampleController
#    view: hyperion.view.simple_gui_examples.example_instrument_gui/ExampleGui
#    dummy: True
#    settings:
#    output: True
#  ExampleInstrument_3:
#    port: COM0
#    instrument: hyperion.instrument.example_instrument/ExampleInstrument
#    controller: hyperion.controller.example_controller/ExampleController
#    view: hyperion.view.simple_gui_examples.example_instrument_gui/ExampleGui
#    dummy: True
#    settings:
#    output: True
#  ExampleInstrument_4:
#    port: COM0
#    instrument: hyperion.instrument.example_instrument/ExampleInstrument
#    controller: hyperion.controller.example_controller/ExampleController
#    view: hyperion.view.simple_gui_examples.example_instrument_gui/ExampleGui
#    dummy: True
#    settings:
#    output: True
#  ExampleInstrument_5:
#    port: COM0
#    instrument: hyperion.instrument.example_instrument/ExampleInstrument
#    controller: hyperion.controller.example_controller/ExampleController
#    view: hyperion.view.simple_gui_examples.example_instrument_gui/ExampleGui
#    dummy: True
#    settings:
#    output: True
#  Gui_with_graph:
#    port: COM0
#    instrument: hyperion.instrument.example_instrument/ExampleInstrument
#    controller: hyperion.controller.example_controller/ExampleController
#    graphView:  hyperion.view.simple_gui_examples.example_graph_gui/App
#    dummy: True
#    settings:
#    output: True

MetaInstruments:
  SampleXyzStageMotor:
    x: xMotor
    y: yMotor
    z: testMotor

Measurements:
  # specific for this experiment
  # list of measurement views which need to be loaded and accessible for the main experiment class.
#  exampleMeasurement:
#    view: examples.measurement_gui/App
#    graphView: hyperion.view.osa.osa_gui/DrawSpectrum
  SweepWaveplate:
    view: examples.sweep_variable_waveplate_with_gui.measurement_guis/SweepWaveplatePolarimeterGui
    graphView: examples.sweep_variable_waveplate_with_gui.measurement_guis/SweepWaveplatePolarimeterGraph
    settings:
      start: 2V
      stop: 3V
      step: 0.02V
      stabilization: 10ms
      average: 1
      wavelength: 536nm


Data:
  save_folder: C:\Users\ariel\Desktop\Delft_code\hyperion\
  data_type: txt


